project:
  type: website
  output-dir: docs
  resources:
    - "/.nojekyll"
    - "/infographics/lib/*"
    - "/infographics/svg/*"
    - "/chat/*"

website:
  title: "CStories.app/Beta"
  google-analytics: "G-9Z3CG75J46"
  favicon: "favicon.png"
  navbar:
    left:
      - infographics.qmd
      - news.qmd
    right:
      - about.qmd
  search:
    location: navbar
    type: overlay

format:
  html:
    theme:
      # https://quarto.org/docs/output-formats/html-themes.html#dark-mode
      light: cerulean # cosmo # [flatly, lib/flatly.scss]
      dark: superhero # [cosmo, lib/theme-dark.scss] # [darkly, lib/darkly.scss]
    toc: true
    comments:
      hypothesis:
        showHighlights: false
    execute:
      echo: false
      warning: false

editor: source
