project:
  type: website
  output-dir: docs
  resources:
    - "/.nojekyll"
    - "/infographics/lib/*"
    - "/infographics/svg/*"
    - "/lib/*"

website:
  title: "CStories.app/Beta"
  google-analytics: "G-9Z3CG75J46"
  favicon: "favicon.png"
  navbar:
    left:
      - icon: robot
        href: chat.qmd
      - icon: chat-right-quote-fill
        href: comment.qmd
      - icon: image
        href: infographics.qmd
      - icon: newspaper
        href: news.qmd
    right:
      - about.qmd
  search:
    location: navbar
    type: overlay

format:
  html:
    theme:
      # https://quarto.org/docs/output-formats/html-themes.html#dark-mode
      light: cosmo
      dark: darkly
    toc: true
    comments:
      hypothesis:
        showHighlights: false
    execute:
      echo: false
      warning: false
    include-after-body: "lib/bot.html"
    css:
    - "lib/bot.css"
editor: source
