name: Docker Image Deployment

on:
  push:
    # https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags
    tags:
      - '**'

permissions:
  id-token: write
  contents: read
jobs:
  # pre_notify:
  #   name: Pre Deployment Notification
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: jdcargile/ms-teams-notification@v1.3
  #       with:
  #         github-token: ${{ github.token }}
  #         ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #         notification-summary: ...
  #         notification-color: 808080
  #         timezone: america/new_york

  docker:
    name: Workflow
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "shinyapps/cstories-beta"
      REGISTRY: "integraldma.azurecr.io"

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: AZ CLI Debug
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        run: |
          docker login $REGISTRY --username 00000000-0000-0000-0000-000000000000 --password-stdin <<< $(az acr login --name $REGISTRY --expose-token --output tsv --query accessToken)
        
      - name: Extract metadata for docker image
        id: meta
        uses: docker/metadata-action@v5
        with:  
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          file: Dockerfile
          platforms: linux/amd64

  # post_notify:
  #   name: Post Deployment Notification
  #   runs-on: ubuntu-latest
  #   needs: docker

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: jdcargile/ms-teams-notification@v1.3
  #       with:
  #         github-token: ${{ github.token }}
  #         ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #         notification-summary: ...
  #         notification-color: 00FF00
  #         timezone: america/new_york
